import numpy


def to_bgr(rgb):
    return tuple(int(c) for c in numpy.array(rgb)[::-1])


RED_RGB = (255, 0, 0)
RED = to_bgr(RED_RGB)

GREEN_RGB = (0, 255, 0)
GREEN = to_bgr(GREEN_RGB)

BLUE_RGB = (0, 0, 255)
BLUE = to_bgr(BLUE_RGB)

MAGENTA_RGB = (255, 0, 255)
MAGENTA = to_bgr(MAGENTA_RGB)

WHITE_RGB = (255, 255, 255)
WHITE = to_bgr(WHITE_RGB)

BLACK_RGB = (0, 0, 0)
BLACK = to_bgr(BLACK_RGB)


# ----------------------------

THUMB_COLOUR_RGB = BLUE_RGB
THUMB_COLOUR = to_bgr(THUMB_COLOUR_RGB)

INDEX_COLOUR_RGB = RED_RGB
INDEX_COLOUR = to_bgr(INDEX_COLOUR_RGB)

MIDDLE_COLOUR_RGB = (108, 60, 200)
MIDDLE_COLOUR = to_bgr(MIDDLE_COLOUR_RGB)

RING_COLOUR_RGB = GREEN_RGB
RING_COLOUR = to_bgr(RING_COLOUR_RGB)

PINKY_COLOUR_RGB = (255, 32, 193)
PINKY_COLOUR = to_bgr(PINKY_COLOUR_RGB)

PALM_COLOUR_RGB = (123, 123, 125)
PALM_COLOUR = to_bgr(PALM_COLOUR_RGB)
